# Initial preprocessing

This notebook explores data but not in a statistical way. Instead it looks into number of features their types. String types ie. object in pandas notation are explored a little bit deeper

In [1]:
import pandas

In [2]:
df = pandas.read_csv('../data/US_Accidents_Dec21_updated.csv')

In [3]:
print(f"len(df)={len(df)}")
print("")
print("col names and types")
print("------------------------------------")
print(df.dtypes)
print(f"len(df.dtypes)={len(df.dtypes)}")

len(df)=2845342

col names and types
------------------------------------
ID                        object
Severity                   int64
Start_Time                object
End_Time                  object
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description               object
Number                   float64
Street                    object
Side                      object
City                      object
County                    object
State                     object
Zipcode                   object
Country                   object
Timezone                  object
Airport_Code              object
Weather_Timestamp         object
Temperature(F)           float64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction            object
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition         object
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
dtype: object
len(df.dtypes)=47

In [4]:
useless_columns = ['ID','Country']

In [1]:
%matplotlib widget
df['Severity'].value_counts().sort_index().plot(kind='bar')

NameError: name 'df' is not defined

## Object datatypes

In [5]:
object_cols = df.columns[df.dtypes=='object']
objects = df[object_cols]
objects

,ID,Start_Time,End_Time,Description,Street,Side,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Wind_Direction,Weather_Condition,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,2016-02-08 00:37:08,2016-02-08 06:37:08,Between Sawmill Rd/Exit 20 and OH-315/Olentang...,Outerbelt E,R,Dublin,Franklin,OH,43017,US,US/Eastern,KOSU,2016-02-08 00:53:00,SW,Light Rain,Night,Night,Night,Night
1,A-2,2016-02-08 05:56:20,2016-02-08 11:56:20,At OH-4/OH-235/Exit 41 - Accident.,I-70 E,R,Dayton,Montgomery,OH,45424,US,US/Eastern,KFFO,2016-02-08 05:58:00,Calm,Light Rain,Night,Night,Night,Night
2,A-3,2016-02-08 06:15:39,2016-02-08 12:15:39,At I-71/US-50/Exit 1 - Accident.,I-75 S,R,Cincinnati,Hamilton,OH,45203,US,US/Eastern,KLUK,2016-02-08 05:53:00,Calm,Overcast,Night,Night,Night,Day
3,A-4,2016-02-08 06:51:45,2016-02-08 12:51:45,At Dart Ave/Exit 21 - Accident.,I-77 N,R,Akron,Summit,OH,44311,US,US/Eastern,KAKR,2016-02-08 06:54:00,Calm,Overcast,Night,Night,Day,Day
4,A-5,2016-02-08 07:53:43,2016-02-08 13:53:43,At Mitchell Ave/Exit 6 - Accident.,I-75 S,R,Cincinnati,Hamilton,OH,45217,US,US/Eastern,KLUK,2016-02-08 07:53:00,WSW,Light Rain,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2845337,A-2845338,2019-08-23 18:03:25,2019-08-23 18:32:01,At Market St - Accident.,Pomona Fwy E,R,Riverside,Riverside,CA,92501,US,US/Pacific,KRAL,2019-08-23 17:53:00,W,Fair,Day,Day,Day,Day
2845338,A-2845339,2019-08-23 19:11:30,2019-08-23 19:38:23,At Camino Del Rio/Mission Center Rd - Accident.,I-8 W,R,San Diego,San Diego,CA,92108,US,US/Pacific,KMYF,2019-08-23 18:53:00,SW,Fair,Day,Day,Day,Day
2845339,A-2845340,2019-08-23 19:00:21,2019-08-23 19:28:49,At Glassell St/Grand Ave - Accident. in the ri...,Garden Grove Fwy,R,Orange,Orange,CA,92866,US,US/Pacific,KSNA,2019-08-23 18:53:00,SSW,Partly Cloudy,Day,Day,Day,Day
2845340,A-2845341,2019-08-23 19:00:21,2019-08-23 19:29:42,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,San Diego Fwy S,R,Culver City,Los Angeles,CA,90230,US,US/Pacific,KSMO,2019-08-23 18:51:00,SW,Fair,Day,Day,Day,Day
2845341,A-2845342,2019-08-23 18:52:06,2019-08-23 19:21:31,At Highland Ave/Arden Ave - Accident.,CA-210 W,R,Highland,San Bernardino,CA,92346,US,US/Pacific,KSBD,2019-08-23 20:50:00,SW,Fair,Day,Day,Day,Day

In [6]:
print("Some features are very high in cardinality")
{col:len(df[col].unique()) for col in objects}

Some features are very high in cardinality

{'ID': 2845342,
 'Start_Time': 1959333,
 'End_Time': 2351505,
 'Description': 1174563,
 'Street': 159652,
 'Side': 3,
 'City': 11682,
 'County': 1707,
 'State': 49,
 'Zipcode': 363086,
 'Country': 1,
 'Timezone': 5,
 'Airport_Code': 2005,
 'Weather_Timestamp': 474215,
 'Wind_Direction': 25,
 'Weather_Condition': 128,
 'Sunrise_Sunset': 3,
 'Civil_Twilight': 3,
 'Nautical_Twilight': 3,
 'Astronomical_Twilight': 3}

In [7]:
# include Number also because its not usefull on it's own without these high cardinality cols
high_card_cols = ['Street','Number','City','County','Airport_Code','Zipcode']
out_of_scope_cols = ['Start_Time','End_Time','Weather_Timestamp','Timezone','Description']

### Weather_Condition

In [8]:
df['Weather_Condition'].value_counts()

Fair                        1107194
Mostly Cloudy                363959
Cloudy                       348767
Partly Cloudy                249939
Clear                        173823
                             ...
Sleet / Windy                     1
Mist / Windy                      1
Blowing Sand                      1
Heavy Freezing Rain               1
Thunder and Hail / Windy          1
Name: Weather_Condition, Length: 127, dtype: int64

In [9]:
weathers = df['Weather_Condition'].value_counts().index
[w for w in weathers if 'Windy' in w]

['Fair / Windy',
 'Cloudy / Windy',
 'Mostly Cloudy / Windy',
 'Partly Cloudy / Windy',
 'Light Rain / Windy',
 'Light Snow / Windy',
 'Rain / Windy',
 'Heavy Rain / Windy',
 'Haze / Windy',
 'Snow / Windy',
 'Heavy T-Storm / Windy',
 'Fog / Windy',
 'T-Storm / Windy',
 'Thunder / Windy',
 'Heavy Snow / Windy',
 'Blowing Dust / Windy',
 'Light Drizzle / Windy',
 'Blowing Snow / Windy',
 'Wintry Mix / Windy',
 'Smoke / Windy',
 'Light Freezing Rain / Windy',
 'Squalls / Windy',
 'Snow and Sleet / Windy',
 'Widespread Dust / Windy',
 'Light Snow and Sleet / Windy',
 'Drizzle / Windy',
 'Light Sleet / Windy',
 'Light Rain Shower / Windy',
 'Patches of Fog / Windy',
 'Thunder / Wintry Mix / Windy',
 'Sand / Windy',
 'Snow and Thunder / Windy',
 'Freezing Rain / Windy',
 'Sand / Dust Whirlwinds / Windy',
 'Heavy Rain Shower / Windy',
 'Sleet / Windy',
 'Mist / Windy',
 'Thunder and Hail / Windy']

Trying to reduce number of classes. Checking that windy present means that Wind_Direction is also present ie. it is not calm.

In [10]:
contain_windy_and_calm = df['Weather_Condition'].str.contains('Windy',na=False) & df['Wind_Direction'].str.contains('Calm', na=False)
df[contain_windy_and_calm][['Weather_Condition','Wind_Direction']]

Empty DataFrame
Columns: [Weather_Condition, Wind_Direction]
Index: []

We can see that wind direction is present everytime the weather is windy. So the **Windy** weather condition will be removed.

Also checking how many weather types contain multiple descriptions.

In [11]:
[w for w in weathers if '/' in w]

['Fair / Windy',
 'Cloudy / Windy',
 'Mostly Cloudy / Windy',
 'Partly Cloudy / Windy',
 'Light Rain / Windy',
 'Light Snow / Windy',
 'Rain / Windy',
 'N/A Precipitation',
 'Heavy Rain / Windy',
 'Haze / Windy',
 'Snow / Windy',
 'Heavy T-Storm / Windy',
 'Fog / Windy',
 'T-Storm / Windy',
 'Thunder / Windy',
 'Heavy Snow / Windy',
 'Blowing Dust / Windy',
 'Light Drizzle / Windy',
 'Blowing Snow / Windy',
 'Wintry Mix / Windy',
 'Smoke / Windy',
 'Light Freezing Rain / Windy',
 'Squalls / Windy',
 'Snow and Sleet / Windy',
 'Widespread Dust / Windy',
 'Light Snow and Sleet / Windy',
 'Sand / Dust Whirlwinds',
 'Drizzle / Windy',
 'Light Sleet / Windy',
 'Light Rain Shower / Windy',
 'Thunder / Wintry Mix',
 'Patches of Fog / Windy',
 'Thunder / Wintry Mix / Windy',
 'Sand / Windy',
 'Snow and Thunder / Windy',
 'Freezing Rain / Windy',
 'Sand / Dust Whirlwinds / Windy',
 'Sand / Dust Whirls Nearby',
 'Heavy Rain Shower / Windy',
 'Sleet / Windy',
 'Mist / Windy',
 'Thunder and Hail / Windy']

Splitting weathers into an array and removing windy weather condition.

In [12]:
def map_weather_to_arr(weather_str):
    return [weather.strip() for weather in weather_str.split(' / ')]

def remove_windy(weather_arr):
    try:
        weather_arr.remove('Windy')
    except ValueError as e:
        pass
    return weather_arr

df['Weather_Condition_Arr']=df['Weather_Condition'].map(map_weather_to_arr,na_action='ignore').map(remove_windy,na_action='ignore')
preprocessed_columns = ['Weather_Condition']

Mostly additional weather descriptions are windy. Exceptions are: **Dust Whirlwinds**, **Dust Whirls Nearby** and **Wintry Mix**. We'll check actually how many of those conditions are labeled in *preprocessing* notebook.

## Encoding wind direction

In [13]:
def map_wind(wind_str, neg_direction,pos_direction):
    if wind_str=='Calm':
        return 0
    
    n = len(wind_str)
    s = 0
    for char in wind_str:
        char_val = 0
        if char==pos_direction:
            char_val = 1
        if char==neg_direction:
            char_val = -1
        s += char_val
    return s/n

map_sn = lambda wind_str: map_wind(wind_str,'S','N')
map_ew = lambda wind_str: map_wind(wind_str,'E','W')

df['Wind_SN'] = df['Wind_Direction'].map(map_sn, na_action='ignore')
df['Wind_EW'] = df['Wind_Direction'].map(map_ew, na_action='ignore')
df[['Wind_SN','Wind_EW']]
winds = df[['Wind_SN','Wind_EW']]
encoded_cols = ['Wind_Direction']
winds

          Wind_SN   Wind_EW
0       -0.500000  0.500000
1        0.000000  0.000000
2        0.000000  0.000000
3        0.000000  0.000000
4       -0.333333  0.666667
...           ...       ...
2845337  0.000000  1.000000
2845338 -0.500000  0.500000
2845339 -0.666667  0.333333
2845340 -0.500000  0.500000
2845341 -0.500000  0.500000

[2845342 rows x 2 columns]

## Feature selection

In [14]:
drop_cols = useless_columns + high_card_cols + out_of_scope_cols + encoded_cols + preprocessed_columns
df = df.drop(drop_cols, axis='columns')

In [15]:
df

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Side,State,Temperature(F),Wind_Chill(F),...,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Weather_Condition_Arr,Wind_SN,Wind_EW
0,3,40.108910,-83.092860,40.112060,-83.031870,3.230,R,OH,42.1,36.1,...,False,False,False,Night,Night,Night,Night,[Light Rain],-0.500000,0.500000
1,2,39.865420,-84.062800,39.865010,-84.048730,0.747,R,OH,36.9,NaN,...,False,False,False,Night,Night,Night,Night,[Light Rain],0.000000,0.000000
2,2,39.102660,-84.524680,39.102090,-84.523960,0.055,R,OH,36.0,NaN,...,False,False,False,Night,Night,Night,Day,[Overcast],0.000000,0.000000
3,2,41.062130,-81.537840,41.062170,-81.535470,0.123,R,OH,39.0,NaN,...,False,False,False,Night,Night,Day,Day,[Overcast],0.000000,0.000000
4,3,39.172393,-84.492792,39.170476,-84.501798,0.500,R,OH,37.0,29.8,...,False,False,False,Day,Day,Day,Day,[Light Rain],-0.333333,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2845337,2,34.002480,-117.379360,33.998880,-117.370940,0.543,R,CA,86.0,86.0,...,False,False,False,Day,Day,Day,Day,[Fair],0.000000,1.000000
2845338,2,32.766960,-117.148060,32.765550,-117.153630,0.338,R,CA,70.0,70.0,...,False,False,False,Day,Day,Day,Day,[Fair],-0.500000,0.500000
2845339,2,33.775450,-117.847790,33.777400,-117.857270,0.561,R,CA,73.0,73.0,...,False,False,False,Day,Day,Day,Day,[Partly Cloudy],-0.666667,0.333333
2845340,2,33.992460,-118.403020,33.983110,-118.395650,0.772,R,CA,71.0,71.0,...,False,False,False,Day,Day,Day,Day,[Fair],-0.500000,0.500000
2845341,2,34.133930,-117.230920,34.137360,-117.239340,0.537,R,CA,79.0,79.0,...,False,False,False,Day,Day,Day,Day,[Fair],-0.500000,0.500000

# Final features for initial feature selection

In [16]:
print("")
print("col names and types")
print("------------------------------------")
print(df.dtypes)
print(f"len(df.dtypes)={len(df.dtypes)}")

col names and types
------------------------------------
Severity                   int64
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Side                      object
State                     object
Temperature(F)           float64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Speed(mph)          float64
Precipitation(in)        float64
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
Weather_Condition_Arr     object
Wind_SN                  float64
Wind_EW                  float64
dtype: object
len(df.dtypes)=35

In [17]:
df.to_csv('../data/dataset_initial.csv',index=False)